### ISSUE TITLE
Invalid schema in GetPeersResponse

### ISSUE THREAD

**Issue by dapplion** [ethereum/beacon-APIs#237]
The response schema for GetPeersResponse is invalid according to [AJV](https://ajv.js.org)

```
     Error: "nullable" cannot be used without "type"
      at getSchemaTypes (node_modules/ajv/lib/compile/validate/dataType.ts:26:13)
      at typeAndKeywords (node_modules/ajv/lib/compile/validate/index.ts:159:31)
      at subSchemaObjCode (node_modules/ajv/lib/compile/validate/index.ts:147:3)
      at subschemaCode (node_modules/ajv/lib/compile/validate/index.ts:124:7)
```

Rendered the schema looks like

```json
                          "enr": {
                            "allOf": [
                              {
                                "type": "string",
                                "description": "Ethereum node record. [Read more](https://eips.ethereum.org/EIPS/eip-778)",
                                "example": "enr:-IS4QHCYrYZbAKWCBRlAy5zzaDZXJBGkcnh4MHcBFZntXNFrdvJjX04jRzjzCBOonrkTfj499SZuOh8R33Ls8RRcy5wBgmlkgnY0gmlwhH8AAAGJc2VjcDI1NmsxoQPKY0yuDUmstAHYpMa2_oxVtw0RW_QAdpzBQA8yWM0xOIN1ZHCCdl8"
                              },
                              {
                                "nullable": true
                              }
                            ]
                          },
```

Because of the allOf syntax nullable is not in the same block as type.

**Comment by mpetrunic** [comment]
Hmm this looks like ajv or openapi schema bug. Afaik this is a legit way to reuse existing type and make it nullable

**Comment by rolfyone** [comment]
I checked our v.2.3.0 release against the online swagger editor and it's not raising errors - are we ok to close this issue @dapplion ?
