### ISSUE TITLE
"Could not render _t, see the console."

### ISSUE THREAD

**Issue by eliotstock** [ethereum/beacon-APIs#266]
I've never been able to get the API client webpage/docs at https://ethereum.github.io/beacon-APIs/ to work.

Steps to repro:

1. Go to https://ethereum.github.io/beacon-APIs/
2. Optionally, change the `server_url` to a known good server
3. Go to any endpoint/method and click 'Try it out'
4. Enter params and click 'Execute'

Result:

UI says: `Could not render _t, see the console.`
Console says:

```
react-dom.production.min.js:216 TypeError: Cannot read properties of null (reading 'get')
    at Ue.render (live-response.jsx:55:29)
    at Hi (react-dom.production.min.js:187:188)
    at Wi (react-dom.production.min.js:186:173)
    at Ks (react-dom.production.min.js:269:427)
    at Il (react-dom.production.min.js:250:347)
    at Ol (react-dom.production.min.js:250:278)
    at Cl (react-dom.production.min.js:250:138)
    at bl (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
cs @ react-dom.production.min.js:216
r.payload @ react-dom.production.min.js:217
da @ react-dom.production.min.js:130
Wi @ react-dom.production.min.js:184
Ks @ react-dom.production.min.js:269
Il @ react-dom.production.min.js:250
Ol @ react-dom.production.min.js:250
Cl @ react-dom.production.min.js:250
bl @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Jo @ react-dom.production.min.js:122
Zo @ react-dom.production.min.js:123
Go @ react-dom.production.min.js:122
wl @ react-dom.production.min.js:244
notify @ Subscription.js:19
t.notifyNestedSubs @ Subscription.js:90
t.handleChangeWrapper @ Subscription.js:95
v @ redux.js:296
(anonymous) @ utils.js:180
(anonymous) @ redux.js:546
(anonymous) @ actions.js:482
Promise.catch (async)
(anonymous) @ actions.js:475
(anonymous) @ utils.js:177
(anonymous) @ redux.js:546
(anonymous) @ wrap-actions.js:33
n @ system.js:175
(anonymous) @ system.js:487
(anonymous) @ actions.js:499
(anonymous) @ utils.js:177
(anonymous) @ redux.js:546
(anonymous) @ spec-wrap-actions.js:9
n @ system.js:175
(anonymous) @ system.js:487
(anonymous) @ execute.jsx:66
(anonymous) @ execute.jsx:80
(anonymous) @ execute.jsx:90
Ve @ react-dom.production.min.js:52
Ge @ react-dom.production.min.js:52
(anonymous) @ react-dom.production.min.js:53
On @ react-dom.production.min.js:100
jn @ react-dom.production.min.js:101
(anonymous) @ react-dom.production.min.js:113
De @ react-dom.production.min.js:292
(anonymous) @ react-dom.production.min.js:50
Mn @ react-dom.production.min.js:105
Xt @ react-dom.production.min.js:75
Qt @ react-dom.production.min.js:74
t.unstable_runWithPriority @ scheduler.production.min.js:18
Jo @ react-dom.production.min.js:122
Re @ react-dom.production.min.js:292
Zt @ react-dom.production.min.js:73
error-boundary.jsx:18 TypeError: Cannot read properties of null (reading 'get')
    at Ue.render (live-response.jsx:55:29)
    at Hi (react-dom.production.min.js:187:188)
    at Wi (react-dom.production.min.js:186:173)
    at Ks (react-dom.production.min.js:269:427)
    at Il (react-dom.production.min.js:250:347)
    at Ol (react-dom.production.min.js:250:278)
    at Cl (react-dom.production.min.js:250:138)
    at bl (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343) {componentStack: '\n    at Ue (https://ethereum.github.io/beacon-APIs…o/beacon-APIs/dist/swagger-ui-bundle.js:2:211217)'}
```

Expected result:

Endpoint is hit and response is rendered.

**Comment by rolfyone** [comment]
I downloaded locally and ran in case it was something that would work locally but not hosted, and it does appear broken, but I'm not going to get a chance to look at this further now. 
If anyone would like to investigate, any time you press execute whether you change the server_url or not, this problem occurs, and it doesn't appear to make a http request, so it's likely a javascript error before the request is even made.
As a work around, i believe most beacon-node implementations do offer a swagger-ui of some type, you could attempt to use the one built into the beacon-api you're using.

**Comment by nflaig** [comment]
This issue seems resolved, I am able to query endpoints via the explorer hosted on https://ethereum.github.io/beacon-APIs. 

Depending on the configuration of the server that gets queried the request might fail due to [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS). In this case, the server needs to explicitly whitelist the domain hosting the explorer or allow request from all domains by setting `*`.

e.g. `Access-Control-Allow-Origin: *`
